name: Playwright Testing

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  Playwright_Testing:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test ChildWindowHandling.spec.js

      # Install Allure Commandline
      - name: Install Allure Commandline
        run: |
          npm install -g allure-commandline --save-dev

      # Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      # Upload Allure report as an artifact
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report/ # Ensure path is correct and directory exists

  # Optionally, serve the report (can be used in GitHub pages or another server)
  deploy:
    runs-on: ubuntu-latest
    needs: Playwright_Testing # Ensures deploy runs after Playwright_Testing job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Serve Allure report
        run: |
          npm install -g http-server
          http-server ./allure-report -p 8000
