name: Playwright Testing

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with Allure reporter
        run: npx playwright test Hooks1.spec.js --reporter=allure-playwright

      # Check if allure-results directory is populated with results
      - name: List contents of allure-results directory (debug)
        run: |
          if [ -d allure-results ]; then
            echo "allure-results directory exists and contains files:"
            ls -R allure-results
          else
            echo "Directory allure-results not found or empty."
          fi

      # Install Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline

      # Generate Allure report from allure-results
      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      # List contents of allure-report directory (debug)
      - name: List contents of allure-report directory (debug)
        run: |
          if [ -d allure-report ]; then
            echo "allure-report directory exists and contains files:"
            ls -R allure-report
          else
            echo "Directory allure-report not found or empty."
          fi

      # Upload Allure report as artifact only if directory exists
      - name: Upload Allure report as artifact
        run: |
          if [ -d allure-report ]; then
            echo "Uploading allure-report as artifact"
            tar -czf allure-report.tar.gz -C allure-report .
            curl -X POST --url https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/allure-report --data-binary @allure-report.tar.gz
          else
            echo "allure-report directory not found. Skipping upload."
          fi

      # Display the link to the generated Allure report
      - name: Display Allure report link
        run: |
          echo "Allure report is available at: https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}"
